from typing import Dict, List, Optional

from app.alphabet.spec import (
    EXT, FOLD, HALF,
    M_HOOK, M_ZIGZAG,
    T_ACROSS, T_OUT, T_TUCKED, T_UP,
    LetterSpec,
)

ASL: List[LetterSpec] = [
    LetterSpec("A", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, hint="fist, thumb pressed to the side"),
    LetterSpec("B", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": EXT},
               thumb=T_ACROSS, spread=False,
               hint="four fingers straight and together, thumb across the palm"),
    LetterSpec("C", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_OUT, spread=False, apart=("index", "middle"),
               hint="hand as a half circle, ring stays open"),
    LetterSpec("D", {"index": EXT, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_OUT, touch=("middle",),
               hint="index up, other fingers form a ring with the thumb"),
    LetterSpec("E", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_ACROSS, spread=False,
               hint="fingers bent as hooks, thumb under them"),
    LetterSpec("F", {"index": HALF, "middle": EXT, "ring": EXT, "pinky": EXT},
               thumb=T_OUT, touch=("index",),
               hint="thumb and index make a ring, three fingers up"),
    LetterSpec("G", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, fingers_dir="left",
               hint="index horizontal, thumb parallel to it"),
    LetterSpec("H", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, fingers_dir="left",
               hint="index and middle together, pointing sideways"),
    LetterSpec("I", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_ACROSS, hint="pinky up only"),
    LetterSpec("J", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_ACROSS, motion=M_HOOK,
               hint="pinky up plus a J hook motion"),
    LetterSpec("K", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_UP, spread=True, touch=("middle",),
               hint="index and middle up in a V, thumb between them"),
    LetterSpec("L", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, fingers_dir="up",
               hint="index up, thumb out, an L angle"),
    LetterSpec("M", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_TUCKED, thumb_under="ring", fingers_dir="down",
               hint="three fingers over the hidden thumb"),
    LetterSpec("N", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_TUCKED, thumb_under="middle", fingers_dir="down",
               hint="two fingers over the hidden thumb"),
    LetterSpec("O", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_OUT, spread=False, touch=("index", "middle"),
               hint="all fingers form a closed ring"),
    LetterSpec("P", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_UP, spread=True, fingers_dir="down",
               hint="like K but the hand points down"),
    LetterSpec("Q", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, fingers_dir="down",
               hint="like G but pointing down"),
    LetterSpec("R", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, crossed=True, fingers_dir="up",
               hint="index and middle crossed"),
    LetterSpec("S", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, fingers_dir="up",
               hint="fist, thumb over the fingers"),
    LetterSpec("T", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_TUCKED, thumb_under="index", fingers_dir="up",
               hint="thumb between index and middle"),
    LetterSpec("U", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, crossed=False, fingers_dir="up",
               hint="index and middle up, held together"),
    LetterSpec("V", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=True, fingers_dir="up",
               hint="index and middle up and spread, victory"),
    LetterSpec("W", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": FOLD},
               thumb=T_ACROSS, spread=True,
               hint="three fingers spread like a fan"),
    LetterSpec("X", {"index": HALF, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, hint="index bent as a hook"),
    LetterSpec("Y", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_OUT, hint="thumb and pinky out to the sides"),
    LetterSpec("Z", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, motion=M_ZIGZAG,
               hint="index draws a Z zigzag"),
]

BY_LETTER: Dict[str, LetterSpec] = {s.letter: s for s in ASL}
SPELLABLE = set(BY_LETTER) | {" "}

def spec_for(letter: str) -> Optional[LetterSpec]:
    return BY_LETTER.get(letter.upper())

__all__ = ["ASL", "BY_LETTER", "SPELLABLE", "spec_for"]