from typing import Dict, List, Optional, Set

from app.alphabet.spec import (
    EXT, FOLD, HALF,
    M_CIRCLE, M_DOWN, M_SHAKE, M_ZIGZAG,
    T_ACROSS, T_OUT, T_TUCKED, T_UP,
    LetterSpec,
)

RSL: List[LetterSpec] = [
    LetterSpec("А", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, hint="fist, thumb at the side"),
    LetterSpec("Б", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_UP, fingers_dir="up",
               hint="index up, thumb set up and out"),
    LetterSpec("В", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": EXT},
               thumb=T_OUT, spread=False,
               hint="four fingers together, thumb out to the side"),
    LetterSpec("Г", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, fingers_dir="left",
               hint="index horizontal, thumb up"),
    LetterSpec("Д", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, spread=True, fingers_dir="down",
               hint="index and middle down like a roof"),
    LetterSpec("Е", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_ACROSS, spread=False,
               hint="fingers bent as hooks, thumb pressed"),
    LetterSpec("Ж", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": FOLD},
               thumb=T_OUT, spread=True,
               hint="three fingers spread like a fan"),
    LetterSpec("З", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, motion=M_ZIGZAG,
               hint="index draws a zigzag"),
    LetterSpec("И", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, fingers_dir="up",
               hint="index and middle up, held together"),
    LetterSpec("Й", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, motion=M_SHAKE,
               hint="like I plus a short shake"),
    LetterSpec("К", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_UP, spread=True, touch=("middle",),
               hint="index and middle spread, thumb between them"),
    LetterSpec("Л", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=True, fingers_dir="down",
               hint="index and middle down and spread"),
    LetterSpec("М", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, fingers_dir="down",
               hint="three fingers down, held together"),
    LetterSpec("Н", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, fingers_dir="left",
               hint="index and middle sideways, held together"),
    LetterSpec("О", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_OUT, spread=False, touch=("index", "middle"),
               hint="all fingers form a closed ring"),
    LetterSpec("П", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_TUCKED, spread=False, fingers_dir="down",
               hint="two fingers down, parallel"),
    LetterSpec("Р", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, fingers_dir="up",
               hint="index up, thumb pressed"),
    LetterSpec("С", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_OUT, spread=False, apart=("index", "middle"), fingers_dir="up",
               hint="hand as a half circle, ring stays open"),
    LetterSpec("Т", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": FOLD},
               thumb=T_ACROSS, spread=False, fingers_dir="left",
               hint="three fingers together, pointing sideways"),
    LetterSpec("У", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_OUT, hint="pinky and thumb set apart"),
    LetterSpec("Ф", {"index": HALF, "middle": HALF, "ring": EXT, "pinky": EXT},
               thumb=T_OUT, touch=("index",),
               hint="thumb and index make a ring, two fingers up"),
    LetterSpec("Х", {"index": HALF, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_ACROSS, hint="index bent as a hook"),
    LetterSpec("Ц", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, motion=M_DOWN,
               hint="index up plus a short move down"),
    LetterSpec("Ч", {"index": EXT, "middle": EXT, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, spread=False, fingers_dir="left",
               hint="two fingers sideways, thumb set apart"),
    LetterSpec("Ш", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": FOLD},
               thumb=T_ACROSS, spread=True, fingers_dir="up",
               hint="three fingers up and spread"),
    LetterSpec("Щ", {"index": EXT, "middle": EXT, "ring": EXT, "pinky": FOLD},
               thumb=T_ACROSS, spread=True, motion=M_DOWN,
               hint="like SH plus a move down"),
    LetterSpec("Ъ", {"index": HALF, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, motion=M_CIRCLE,
               hint="hook plus a circle motion"),
    LetterSpec("Ы", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_ACROSS, fingers_dir="left",
               hint="pinky pointing sideways"),
    LetterSpec("Ь", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_ACROSS, fingers_dir="up",
               hint="pinky up"),
    LetterSpec("Э", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_OUT, spread=False, fingers_dir="left",
               hint="half circle turned sideways"),
    LetterSpec("Ю", {"index": FOLD, "middle": FOLD, "ring": FOLD, "pinky": EXT},
               thumb=T_UP, hint="thumb up and pinky out"),
    LetterSpec("Я", {"index": EXT, "middle": FOLD, "ring": FOLD, "pinky": FOLD},
               thumb=T_OUT, fingers_dir="down",
               hint="index down, thumb to the side"),
    LetterSpec("Ё", {"index": HALF, "middle": HALF, "ring": HALF, "pinky": HALF},
               thumb=T_ACROSS, spread=False, motion=M_SHAKE,
               hint="like E plus a shake"),
]

BY_LETTER: Dict[str, LetterSpec] = {s.letter: s for s in RSL}
SPELLABLE = set(BY_LETTER) | {" "}

UNVERIFIED: Set[str] = {
    "Б", "Д", "Ж", "Л", "М", "Н", "П", "Т", "У", "Ф", "Х",
    "Ц", "Ч", "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я", "Ё",
}

def spec_for(letter: str) -> Optional[LetterSpec]:
    return BY_LETTER.get(letter.upper())

__all__ = ["RSL", "BY_LETTER", "SPELLABLE", "UNVERIFIED", "spec_for"]